// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo9xPyVKrcqqvXf2TS4djWSR3tYF4irH8',
    appId: '1:462976641158:web:870c669d9dc215e20d4907',
    messagingSenderId: '462976641158',
    projectId: 'food-app-ea89d',
    authDomain: 'food-app-ea89d.firebaseapp.com',
    storageBucket: 'food-app-ea89d.appspot.com',
    measurementId: 'G-TFZN1PP9KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthvU4pn_7YNErSu5Y2zGDtnyNtYYpMyk',
    appId: '1:462976641158:android:bcf648b4990c0a930d4907',
    messagingSenderId: '462976641158',
    projectId: 'food-app-ea89d',
    storageBucket: 'food-app-ea89d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4be26NDpE3Hc_GSGH-xhD9Vj9wdSL_0',
    appId: '1:462976641158:ios:e4faf9e76ba19dc20d4907',
    messagingSenderId: '462976641158',
    projectId: 'food-app-ea89d',
    storageBucket: 'food-app-ea89d.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4be26NDpE3Hc_GSGH-xhD9Vj9wdSL_0',
    appId: '1:462976641158:ios:e4faf9e76ba19dc20d4907',
    messagingSenderId: '462976641158',
    projectId: 'food-app-ea89d',
    storageBucket: 'food-app-ea89d.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo9xPyVKrcqqvXf2TS4djWSR3tYF4irH8',
    appId: '1:462976641158:web:5737db1b23e0a38c0d4907',
    messagingSenderId: '462976641158',
    projectId: 'food-app-ea89d',
    authDomain: 'food-app-ea89d.firebaseapp.com',
    storageBucket: 'food-app-ea89d.appspot.com',
    measurementId: 'G-ZZX5CVM8G4',
  );
}
